name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Lint execution
        run: npm run lint
      - name: Testing
        run: npm run test-headless
      - name: Build Project
        run: npm run build



